### ISSUE TITLE
autodl-irssi update errors

### ISSUE THREAD

**Issue by kvn1351** [horjulf/docker-rutorrent-autodl#15]
This happens on a fresh docker :/

Any ideas?

![image](https://user-images.githubusercontent.com/11823348/76687485-afa67900-6624-11ea-9efe-13296d31e345.png)

The only thing I could find online was this:
https://github.com/autodl-community/autodl-irssi/issues/185
https://plaza.quickbox.io/t/update-autodl-irssi/8469

**Comment by MGoPhishin** [comment]
Encountering this same issue described above since a few days ago on 2.6.2. In addition, if my IRC trackers attempt to pick something up, I get a similar error stating "Could not parse HTTP Response"

**Comment by lun4r** [comment]
I've got same issue

**Comment by akzkak** [comment]
Fixed by reverting back to previous version in "/rutorrent/.irssi/scripts/AutodlIrssi" directory.

Stop container and paste [v.2.6.1](https://github.com/autodl-community/autodl-irssi/releases/tag/2.6.1) into the dir above.

**Comment by assbaby** [comment]
> Fixed by reverting back to previous version in "/rutorrent/.irssi/scripts/AutodlIrssi" directory.
> 
> Stop container and paste [v.2.6.1](https://github.com/autodl-community/autodl-irssi/releases/tag/2.6.1) into the dir above.

I attempted this, am having a similar issue, and it appears that autodl-irssi updates to 2.6.2 as soon as I start the container again even though it's set not to do in the autodl.cfg

**Comment by horjulf** [comment]
Seems to be related to SSL changes in autodl-irssi upstream, updated the base image to alpine 3.11, can you confirm its fixed in the develop build ?

Tag: `horjulf/rutorrent-autodl:develop`

**Comment by kvn1351** [comment]
> Seems to be related to SSL changes in autodl-irssi upstream, updated the base image to alpine 3.11, can you confirm its fixed in the develop build ?
> 
> Tag: `horjulf/rutorrent-autodl:develop`

![image](https://user-images.githubusercontent.com/11823348/77230255-4d54f780-6b93-11ea-9e05-6ea5f5fe1b2d.png)

Thanks!

**Comment by EsEnZeT** [comment]
@horjulf 

Isn't this more problem, how update of autodl is handled?

```
[cont-init.d] 30-getautodl: executing...
Cloning into '/app/rutorrent/plugins/autodl-irssi'...
Already up to date.
Updating a94f348..b534cbe
error: Your local changes to the following files would be overwritten by merge:
	AutodlIrssi/SslSocket.pm
	AutodlIrssi/Startup.pm
	AutodlIrssi/Updater.pm
Please commit your changes or stash them before you merge.
Aborting
```

for now wiping 'AutodlIrssi' folder and then updating fixes problem.

**Comment by horjulf** [comment]
That means the contents were modified outside of the container, those files are git cloned and updated when the container starts, if you resolved the conflict, it should be an issue anymore.

**Comment by BrandonG777** [comment]
I'm still fighting this. Resolved git conflicts and still getting time out errors. Tried the develop tag but didnt have any luck with that starting with my config.
